name: benchmarks
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/**'
      - 'format/**'
      - 'test/**'
jobs:
    benchmarks:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
        permissions: 
          pull-requests: write 
        steps:
          - uses: actions/checkout@v5
          - uses: julia-actions/setup-julia@v1
            with:
              version: "1"
          - uses: julia-actions/cache@v2
          - uses: julia-actions/julia-buildpkg@v1
          - name: Benchmark
            run: |
              git fetch origin +:refs/remotes/origin/HEAD
              julia --project=benchmark/ -e '
                  using Pkg
                  Pkg.develop(PackageSpec(path=pwd()))
                  Pkg.instantiate()'
              # Pkg.update() allows us to benchmark even when dependencies/compat requirements change
              julia --project=benchmark/ -e '
                  using PkgBenchmark, Loess
                  juliacmd = `$(Base.julia_cmd()) -O3 -e "using Pkg; Pkg.update()"`
                  config = BenchmarkConfig(; id="origin/HEAD", juliacmd)
                  export_markdown("benchmark.md", judge(Loess, config; verbose=true))'
          - name: Comment PR
            uses: thollander/actions-comment-pull-request@v2
            with:
              filePath: "benchmark.md"
              comment_tag: benchmark
